entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: vklstha@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
